name: Latex DevEnv Docker Image Builder

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - latex/**
  pull_request:
    branches: [ main ]

jobs:

  build-and-push-docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2.4.2
      
    - name: Set Up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2.0.0
      
    - name: Login to DockerHub
      uses: docker/login-action@v2.0.0 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build image and push to Docker Hub and GitHub Container Registry
      uses: docker/build-push-action@v3.0.0
      with:
        context: "./latex"
        file: "./latex/Dockerfile"
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/devcontainer-latex:latest
